import { useState, useEffect } from "react";
import API from "../services/api";
import jsPDF from "jspdf";

import ATSCard from "./ATSCard";
import StrengthCard from "./StrengthCard";
import WeaknessCard from "./WeaknessCard";
import MissingSkillsCard from "./MissingSkillsCard";
import SuggestionsCard from "./SuggestionsCard";
import JobRolesCard from "./JobRolesCard";
import InterviewCard from "./InterviewCard";

function AnalyzeResume(){

    const [result,setResult] = useState(null);

    const [loading,setLoading] = useState(false);

    const [progress,setProgress] = useState(0);

    const analyze = async()=>{

        const resumeId =
            localStorage.getItem("resumeId");

        const userId =
            localStorage.getItem("userId");

        if(!resumeId){

            alert("Upload resume first");

            return;

        }

        if(!userId){

            alert("Please login again");

            return;

        }

        let interval;

        try{

            setLoading(true);

            setResult(null);

            setProgress(0);

            interval = setInterval(()=>{

                setProgress((prev)=>{

                    if(prev >= 90){

                        return prev;

                    }

                    return prev + 10;

                });

            },500);

            const response = await API.post(
                `/analysis/${resumeId}/${userId}`
            );

            setResult(response.data);

        }
        catch(error){

            console.log(error);

            if(error.response?.status === 403){

                alert("You are not authorized to analyze this resume.");

            }else{

                alert("Analysis failed");

            }

        }
        finally{

            clearInterval(interval);

            setProgress(100);

            setTimeout(()=>{

                setLoading(false);

            },500);

        }

    };
        useEffect(()=>{

        const resumeId =
            localStorage.getItem("resumeId");

        if(resumeId){

            analyze();

        }

    },[]);

    const downloadPDF = ()=>{

        const doc = new jsPDF();

        let y = 20;

        doc.setFontSize(22);

        doc.text(
            "AI Resume Analysis Report",
            20,
            y
        );

        y += 15;

        doc.setFontSize(12);

        doc.text(
            "Resume Performance & Career Insights",
            20,
            y
        );

        y += 20;

        doc.setFontSize(16);

        doc.text(
            "ATS Score",
            20,
            y
        );

        y += 10;

        doc.setFontSize(14);

        doc.text(
            `${result.atsScore}%`,
            25,
            y
        );

        y += 20;

        const addSection=(title,items)=>{

            doc.setFontSize(15);

            doc.text(
                title,
                20,
                y
            );

            y += 10;

            doc.setFontSize(12);

            items?.forEach((item)=>{

                doc.text(
                    "• " + item,
                    25,
                    y
                );

                y += 8;

                if(y > 270){

                    doc.addPage();

                    y = 20;

                }

            });

            y += 10;

        };

        addSection(
            "Strengths",
            result.strengths
        );

        addSection(
            "Weaknesses",
            result.weaknesses
        );

        addSection(
            "Missing Skills",
            result.missingSkills
        );

        addSection(
            "Suggestions",
            result.suggestions
        );

        addSection(
            "Suitable Job Roles",
            result.suitableJobRoles
        );

        addSection(
            "Interview Questions",
            result.interviewQuestions
        );

        doc.setFontSize(10);

        doc.text(
            "Generated by ResumePilot AI",
            20,
            285
        );

        doc.save(
            "AI_Resume_Analysis_Report.pdf"
        );

    };
        return(

        <div className="analysis-card">

            <h2>
                🤖 Resume Analysis
            </h2>

            <button
                className="analyze-btn"
                onClick={analyze}
                disabled={loading}
            >

                {
                    loading
                    ?
                    "Analyzing..."
                    :
                    "Analyze Resume"
                }

            </button>

            {
                loading && (

                    <div className="ai-loader">

                        <div className="spinner"></div>

                        <h3>

                            🤖 AI Analysis Running...

                        </h3>

                        <div className="progress-bar">

                            <div

                                className="progress-fill"

                                style={{

                                    width:`${progress}%`

                                }}

                            >

                            </div>

                        </div>

                        <h4>

                            {progress}% Completed

                        </h4>

                        <p>

                            {

                                progress < 30

                                ?

                                "📄 Extracting resume information..."

                                :

                                progress < 60

                                ?

                                "🧠 Checking skills and ATS compatibility..."

                                :

                                progress < 90

                                ?

                                "💼 Generating job roles and interview questions..."

                                :

                                "✅ Finalizing report..."

                            }

                        </p>

                    </div>

                )
            }

            {
                result && (

                    <div className="result-container">

                        <div className="dashboard-header">

                            <h2>

                                📈 Resume Insights

                            </h2>

                            <p>

                                AI-powered analysis of your resume

                            </p>

                        </div>

                        <div className="ats-section">

                            <ATSCard
                                score={result.atsScore}
                            />

                        </div>

                        <div className="analysis-grid">

                            <StrengthCard
                                strengths={result.strengths}
                            />

                            <WeaknessCard
                                weaknesses={result.weaknesses}
                            />

                            <MissingSkillsCard
                                skills={result.missingSkills}
                            />

                            <SuggestionsCard
                                suggestions={result.suggestions}
                            />

                        </div>

                        <div className="full-card">

                            <JobRolesCard
                                roles={result.suitableJobRoles}
                            />

                        </div>

                        <div className="full-card">

                            <InterviewCard
                                questions={result.interviewQuestions}
                            />

                        </div>

                        <button
                            className="download-btn"
                            onClick={downloadPDF}
                        >

                            📄 Download Report

                        </button>

                    </div>

                )
            }

        </div>

    );

}

export default AnalyzeResume;